namespace LAB2D.Data
{
    using LAB2D;
    using System;
    using System.Collections.Generic;
    using UnityEngine;

    /// <summary>
    /// 建造所需的一种资源及其数量。
    /// 在 BuildItemDataSO 中配置，实现数据驱动的建造材料需求。
    /// </summary>
    [Serializable]
    public struct ResourceCost
    {
        /// <summary>
        /// 资源名称（对应 ItemData.Name，通过 ItemDataManager 查找 ID）
        /// </summary>
        [Tooltip("资源名称（对应 ItemData.Name，通过 ItemDataManager 查找 ID）")]
        public string ItemName;

        /// <summary>
        /// 所需数量
        /// </summary>
        [Tooltip("所需数量")]
        public int Count;
    }

    /// <summary>
    /// 建造物品数据。
    /// 支持方向变体自动生成：开启 AutoGenerateDirections 后，
    /// 一条配置自动生成 8 个方向变体（T/D/L/R/RT/RD/LT/LD）。
    /// </summary>
    [Serializable]
    public class BuildItemData : ItemData
    {
        /// <summary>
        /// 是否可通行
        /// </summary>
        [Tooltip("是否可通行")]
        public bool IsPass;

        /// <summary>
        /// 是否需要建造
        /// </summary>
        [Tooltip("是否需要建造")]
        public bool IsNeedBuild;

        /// <summary>
        /// 建造所需资源列表（在 SO 中配置）。
        /// 为空时 fallback 到默认 CustomWood x5。
        /// </summary>
        [Tooltip("建造所需资源列表（在 SO 中配置）。为空时 fallback 到默认 CustomWood x5。")]
        public List<ResourceCost> BuildCosts;

        /// <summary>
        /// 是否自动生成 8 方向变体。
        /// 开启后，以本条目的 CnName/Name 为基础，
        /// 自动创建 T/D/L/R/RT/RD/LT/LD 8 个变体。
        /// </summary>
        [Tooltip("开启后，以本条目的 CnName/Name 为基础，自动创建 T/D/L/R/RT/RD/LT/LD 8 个变体。")]
        public bool AutoGenerateDirections;

        /// <summary>
        /// 供暖功率（℃）。&gt;0 表示热源：位于房间内部时向房间提供供暖（房间温度 = 室外 + 保温 + ΣHeatPower）。
        /// 数据驱动：给某建筑配置该值即自动参与供暖，无需改代码。
        /// </summary>
        [Tooltip("供暖功率（℃）。>0 表示热源：位于房间内部时向房间提供供暖")]
        public float HeatPower;

        // 地面视觉模式字段位于基类 ItemData.VisualMode（建筑/背包掉落/资源通用，Clone 继承）。

        /// <summary>
        /// 8 方向变体的中文名称前缀，按从上到下、从左到右排列。
        /// 索引 0-7 对应：左上、上、右上、左、右、左下、下、右下。
        /// </summary>
        public static readonly string[] DirectionCnNames =
        {
            "左上",  // _0
            "上",    // _1
            "右上",  // _2
            "左",    // _3
            "右",    // _4
            "左下",  // _5
            "下",    // _6
            "右下",  // _7
        };

        /// <summary>
        /// 深拷贝一份 BuildItemData（用于生成变体）。
        /// </summary>
        internal BuildItemData Clone()
        {
            return new BuildItemData
            {
                CnName = this.CnName,
                Name = this.Name,
                Info = this.Info,
                IsStackable = this.IsStackable,
                Type = this.Type,
                IsPass = this.IsPass,
                IsNeedBuild = this.IsNeedBuild,
                BuildCosts = this.BuildCosts != null ? new List<ResourceCost>(this.BuildCosts) : null,
                AutoGenerateDirections = false,
                LayerMode = this.LayerMode,
                HeatPower = this.HeatPower,
                VisualMode = this.VisualMode,
            };
        }
    }
}
