namespace LAB2D.Editor
{
    using LAB2D.Data;
    using LAB2D.Item;
    using LAB2D.SO;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using UnityEditor;
    using UnityEngine;
    using UnityEngine.Tilemaps;

    /// <summary>
    /// 建造道具快速创建器。
    /// 从已切割的 Sprite Sheet 一键生成所有 Tile .asset 并追加到目标 DataSO。
    ///
    /// 使用流程：
    /// 1. 将 PNG 放在 Resources/Images/Item/Build/ 并切割好 sprite sheet
    /// 2. 打开本窗口（菜单：工具/建造道具快速创建器）
    /// 3. 拖入贴图 → 自动列出所有 sprite
    /// 4. 填写道具参数
    /// 5. 点击"一键生成"
    ///
    /// 工具会自动完成：
    /// - 为每个 sprite 创建 Tile .asset 到 Resources/Tilemap/Item/Build/
    /// - 在目标 BuildItemDataSO 中追加 BuildItemData 条目
    /// </summary>
    public class BuildItemCreatorWindow : EditorWindow
    {
        private Texture2D sourceTexture;
        private List<Sprite> sprites = new List<Sprite>();
        private bool spritesLoaded;
        private Vector2 spriteScrollPos;

        // 基础参数
        private string cnName = string.Empty;
        private string enName = string.Empty;
        private string info = string.Empty;
        private bool isPass;
        private bool isNeedBuild = true;
        private bool autoGenerateDirections;
        private AItem.ItemTypeEnum itemType = AItem.ItemTypeEnum.Furniture;

        // 目标 SO
        private BuildItemDataSO targetSO;

        // 建造消耗
        private List<BuildCostEntry> buildCosts = new List<BuildCostEntry>();

        // 输出路径
        private const string DefaultTileOutputDir = "Assets/Resources/Tilemap/Item/Build/";

        // UI 折叠状态
        private bool showBuildCosts = true;
        private bool showSpritePreview = true;

        [Serializable]
        private class BuildCostEntry
        {
            public string itemName = string.Empty;
            public int count = 1;
        }

        [MenuItem("工具/建造道具快速创建器")]
        public static void ShowWindow()
        {
            BuildItemCreatorWindow window = GetWindow<BuildItemCreatorWindow>("建造道具创建器");
            window.minSize = new Vector2(420, 560);
            window.Show();
        }

        private void OnGUI()
        {
            EditorGUILayout.Space(5);
            EditorGUILayout.LabelField("建造道具快速创建器", EditorStyles.boldLabel);
            EditorGUILayout.HelpBox(
                "从已切割的 Sprite Sheet 一键生成 Tile .asset 并追加到 DataSO。\n" +
                "步骤：拖入贴图 → 填写参数 → 一键生成",
                MessageType.Info);
            EditorGUILayout.Space(5);

            this.DrawTextureSection();
            EditorGUILayout.Space(5);
            this.DrawConfigSection();
            EditorGUILayout.Space(5);
            this.DrawBuildCostsSection();
            EditorGUILayout.Space(5);
            this.DrawTargetSOSection();
            EditorGUILayout.Space(10);
            this.DrawGenerateButton();
        }

        /// <summary>
        /// 贴图选择区域
        /// </summary>
        private void DrawTextureSection()
        {
            EditorGUILayout.LabelField("1. 选择贴图（已切割 Multiple Sprite）", EditorStyles.boldLabel);

            EditorGUI.BeginChangeCheck();
            this.sourceTexture = (Texture2D)EditorGUILayout.ObjectField(
                "源贴图",
                this.sourceTexture,
                typeof(Texture2D),
                false);
            if (EditorGUI.EndChangeCheck())
            {
                this.LoadSpritesFromTexture();
            }

            if (this.spritesLoaded && this.sprites.Count > 0)
            {
                this.showSpritePreview = EditorGUILayout.Foldout(this.showSpritePreview,
                    $"已检测到 {this.sprites.Count} 个 Sprite", true);

                if (this.showSpritePreview)
                {
                    this.spriteScrollPos = EditorGUILayout.BeginScrollView(
                        this.spriteScrollPos,
                        GUILayout.Height(120));
                    EditorGUILayout.BeginHorizontal();

                    // 使用 GUIStyle 控制预览大小 — 每个 sprite 32x32 缩略图
                    foreach (Sprite sprite in this.sprites)
                    {
                        if (sprite == null)
                        {
                            continue;
                        }

                        EditorGUILayout.BeginVertical(GUILayout.Width(48));
                        // 直接绘制 sprite 纹理区域（简化缩略图）
                        Rect lastRect = GUILayoutUtility.GetRect(40, 40, GUILayout.Width(40), GUILayout.Height(40));
                        GUI.DrawTextureWithTexCoords(lastRect, sprite.texture,
                            new Rect(
                                (float)sprite.rect.x / sprite.texture.width,
                                (float)sprite.rect.y / sprite.texture.height,
                                (float)sprite.rect.width / sprite.texture.width,
                                (float)sprite.rect.height / sprite.texture.height));
                        GUILayout.Label(sprite.name, EditorStyles.miniLabel, GUILayout.Width(44));
                        EditorGUILayout.EndVertical();
                    }

                    EditorGUILayout.EndHorizontal();
                    EditorGUILayout.EndScrollView();
                }

                if (string.IsNullOrEmpty(this.enName))
                {
                    // 自动从第一个 sprite 名推断基础英文名（去掉尾部 _数字）
                    string autoName = this.sprites[0]?.name;
                    if (!string.IsNullOrEmpty(autoName))
                    {
                        int lastUnderscore = autoName.LastIndexOf('_');
                        if (lastUnderscore > 0)
                        {
                            string suffix = autoName.Substring(lastUnderscore + 1);
                            if (int.TryParse(suffix, out _))
                            {
                                autoName = autoName.Substring(0, lastUnderscore);
                            }
                        }

                        this.enName = autoName;
                    }
                }
            }
            else if (this.sourceTexture != null && !this.spritesLoaded)
            {
                EditorGUILayout.HelpBox(
                    "未检测到 Sprite。请确保贴图 Texture Type 为 Sprite (2D and UI)，" +
                    "Sprite Mode 为 Multiple，且已在 Sprite Editor 中完成切割。",
                    MessageType.Warning);
            }
        }

        /// <summary>
        /// 道具配置区域
        /// </summary>
        private void DrawConfigSection()
        {
            EditorGUILayout.LabelField("2. 道具配置", EditorStyles.boldLabel);

            this.cnName = EditorGUILayout.TextField("中文名称", this.cnName);
            this.enName = EditorGUILayout.TextField("英文名称(Name)", this.enName);
            this.info = EditorGUILayout.TextField("描述信息", this.info);
            this.itemType = (AItem.ItemTypeEnum)EditorGUILayout.EnumPopup("道具类型", this.itemType);

            EditorGUILayout.Space(3);
            EditorGUILayout.BeginHorizontal();
            this.isPass = EditorGUILayout.ToggleLeft("可通行", this.isPass, GUILayout.Width(80));
            this.isNeedBuild = EditorGUILayout.ToggleLeft("需要建造", this.isNeedBuild, GUILayout.Width(80));
            this.autoGenerateDirections = EditorGUILayout.ToggleLeft("自动生成8方向变体", this.autoGenerateDirections);
            EditorGUILayout.EndHorizontal();

            if (this.autoGenerateDirections)
            {
                EditorGUILayout.HelpBox(
                    "开启后，系统会从这一条配置自动生成 8 个方向变体" +
                    "（上/下/左/右/左上/右上/左下/右下）。\n" +
                    "Tile 文件名格式：{Name}_0 ~ {Name}_7，对应 8 个方向。",
                    MessageType.Info);
            }

            if (this.isPass && this.isNeedBuild)
            {
                EditorGUILayout.HelpBox(
                    "可通行 + 需要建造：建造过程中可通行（如门），完成后恢复碰撞。",
                    MessageType.Info);
            }

            if (!this.isPass && !this.isNeedBuild)
            {
                EditorGUILayout.HelpBox(
                    "不可通行 + 不需要建造：放置即生效（如装饰墙），直接设置碰撞。",
                    MessageType.Info);
            }
        }

        /// <summary>
        /// 建造消耗区域
        /// </summary>
        private void DrawBuildCostsSection()
        {
            this.showBuildCosts = EditorGUILayout.Foldout(this.showBuildCosts, "3. 建造所需材料（可选）", true);

            if (!this.showBuildCosts)
            {
                return;
            }

            if (this.buildCosts.Count == 0)
            {
                EditorGUILayout.HelpBox(
                    "不配置则使用默认消耗：CustomWood × 5",
                    MessageType.None);
            }

            for (int i = 0; i < this.buildCosts.Count; i++)
            {
                EditorGUILayout.BeginHorizontal();
                this.buildCosts[i].itemName = EditorGUILayout.TextField(
                    "材料名称(Name)",
                    this.buildCosts[i].itemName);
                this.buildCosts[i].count = EditorGUILayout.IntField(
                    "数量",
                    this.buildCosts[i].count);
                if (GUILayout.Button("×", GUILayout.Width(24)))
                {
                    this.buildCosts.RemoveAt(i);
                    i--;
                }

                EditorGUILayout.EndHorizontal();
            }

            EditorGUILayout.BeginHorizontal();
            GUILayout.FlexibleSpace();
            if (GUILayout.Button("+ 添加材料", GUILayout.Width(100)))
            {
                this.buildCosts.Add(new BuildCostEntry());
            }

            EditorGUILayout.EndHorizontal();
        }

        /// <summary>
        /// 目标 DataSO 区域
        /// </summary>
        private void DrawTargetSOSection()
        {
            EditorGUILayout.LabelField("4. 目标 DataSO", EditorStyles.boldLabel);

            this.targetSO = (BuildItemDataSO)EditorGUILayout.ObjectField(
                "BuildItemDataSO",
                this.targetSO,
                typeof(BuildItemDataSO),
                false);

            if (this.targetSO == null)
            {
                EditorGUILayout.HelpBox(
                    "请将 Resources/SO/ 下的 BuildItemDataSO 拖入此处。\n" +
                    "例如：FurnitureItemData、WallItemData、BuildOtherItemData 等。",
                    MessageType.Warning);
            }
        }

        /// <summary>
        /// 生成按钮
        /// </summary>
        private void DrawGenerateButton()
        {
            EditorGUI.BeginDisabledGroup(!this.CanGenerate());
            if (GUILayout.Button("🚀 一键生成所有 Tile + DataSO 条目", GUILayout.Height(40)))
            {
                this.GenerateAll();
            }

            EditorGUI.EndDisabledGroup();

            if (!this.CanGenerate())
            {
                string missing = this.GetMissingRequirements();
                if (!string.IsNullOrEmpty(missing))
                {
                    EditorGUILayout.HelpBox($"还需要：{missing}", MessageType.Warning);
                }
            }
        }

        /// <summary>
        /// 从贴图加载所有 sprite
        /// </summary>
        private void LoadSpritesFromTexture()
        {
            this.sprites.Clear();
            this.spritesLoaded = false;

            if (this.sourceTexture == null)
            {
                return;
            }

            string assetPath = AssetDatabase.GetAssetPath(this.sourceTexture);
            if (string.IsNullOrEmpty(assetPath))
            {
                return;
            }

            // 加载贴图中的所有子资产（sprite 切割后的各个 sprite）
            UnityEngine.Object[] assets = AssetDatabase.LoadAllAssetsAtPath(assetPath);
            foreach (UnityEngine.Object asset in assets)
            {
                if (asset is Sprite sprite)
                {
                    this.sprites.Add(sprite);
                }
            }

            // 按名称排序
            this.sprites = this.sprites
                .OrderBy(s => s.name, new NaturalSortComparer())
                .ToList();

            this.spritesLoaded = this.sprites.Count > 0;
        }

        /// <summary>
        /// 自然排序比较器 — "StoneRoad_2" 排在 "StoneRoad_10" 之前
        /// </summary>
        private class NaturalSortComparer : IComparer<string>
        {
            public int Compare(string x, string y)
            {
                if (x == null || y == null)
                {
                    return string.Compare(x, y, StringComparison.Ordinal);
                }

                // 找到末尾的数字部分进行比较
                int i = x.Length - 1;
                int j = y.Length - 1;

                // 提取尾部数字
                while (i >= 0 && char.IsDigit(x[i]))
                {
                    i--;
                }

                while (j >= 0 && char.IsDigit(y[j]))
                {
                    j--;
                }

                string prefixX = x.Substring(0, i + 1);
                string prefixY = y.Substring(0, j + 1);
                int prefixCmp = string.Compare(prefixX, prefixY, StringComparison.Ordinal);
                if (prefixCmp != 0)
                {
                    return prefixCmp;
                }

                int numX = 0, numY = 0;
                int.TryParse(x.Substring(i + 1), out numX);
                int.TryParse(y.Substring(j + 1), out numY);
                return numX.CompareTo(numY);
            }
        }

        private bool CanGenerate()
        {
            return this.spritesLoaded
                && this.sprites.Count > 0
                && !string.IsNullOrEmpty(this.enName)
                && !string.IsNullOrEmpty(this.cnName)
                && this.targetSO != null;
        }

        private string GetMissingRequirements()
        {
            List<string> missing = new List<string>();
            if (!this.spritesLoaded || this.sprites.Count == 0)
            {
                missing.Add("选择已切割的贴图");
            }

            if (string.IsNullOrEmpty(this.enName))
            {
                missing.Add("填写英文名称");
            }

            if (string.IsNullOrEmpty(this.cnName))
            {
                missing.Add("填写中文名称");
            }

            if (this.targetSO == null)
            {
                missing.Add("选择目标 DataSO");
            }

            return string.Join("、", missing);
        }

        /// <summary>
        /// 一键生成：创建 Tile assets + 更新 DataSO
        /// </summary>
        private void GenerateAll()
        {
            if (!this.CanGenerate())
            {
                return;
            }

            // 确保输出目录存在
            if (!Directory.Exists(DefaultTileOutputDir))
            {
                Directory.CreateDirectory(DefaultTileOutputDir);
                AssetDatabase.Refresh();
            }

            int createdCount = 0;
            List<string> createdAssetPaths = new List<string>();

            foreach (Sprite sprite in this.sprites)
            {
                if (sprite == null)
                {
                    continue;
                }

                string assetPath = Path.Combine(DefaultTileOutputDir, $"{sprite.name}.asset");
                assetPath = AssetDatabase.GenerateUniqueAssetPath(assetPath);

                // 检查是否已存在同名资产
                if (File.Exists(assetPath))
                {
                    Debug.LogWarning($"[BuildItemCreator] 跳过已存在的文件: {assetPath}");
                    continue;
                }

                this.CreateTileAsset(sprite, assetPath);
                createdAssetPaths.Add(assetPath);
                createdCount++;
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            // 延迟更新 DataSO（AssetDatabase 刷新后才能正确设置 sprite 引用）
            EditorApplication.delayCall += () =>
            {
                this.AddToDataSO();
                Debug.Log(
                    $"[BuildItemCreator] 生成完成！\n" +
                    $"  创建 Tile .asset: {createdCount} 个\n" +
                    $"  已追加 DataSO 条目: 1 个 → {this.targetSO.name}\n" +
                    $"  输出目录: {DefaultTileOutputDir}");
            };

            Debug.Log(
                $"[BuildItemCreator] 已创建 {createdCount} 个 Tile asset。" +
                $" DataSO 将在资源刷新后更新。");
        }

        /// <summary>
        /// 创建单个 Tile .asset 文件
        /// </summary>
        private void CreateTileAsset(Sprite sprite, string assetPath)
        {
            Tile tile = ScriptableObject.CreateInstance<Tile>();
            tile.sprite = sprite;
            tile.colliderType = Tile.ColliderType.Sprite;
            AssetDatabase.CreateAsset(tile, assetPath);
        }

        /// <summary>
        /// 向目标 DataSO 追加 BuildItemData 条目
        /// </summary>
        private void AddToDataSO()
        {
            if (this.targetSO == null)
            {
                return;
            }

            SerializedObject so = new SerializedObject(this.targetSO);
            SerializedProperty listProp = so.FindProperty("BuildItemDatas");

            if (listProp == null)
            {
                Debug.LogError("[BuildItemCreator] 无法找到 BuildItemDatas 属性");
                return;
            }

            // 追加新条目
            int newIndex = listProp.arraySize;
            listProp.InsertArrayElementAtIndex(newIndex);
            SerializedProperty elementProp = listProp.GetArrayElementAtIndex(newIndex);

            // 设置各字段
            this.SetSerializedProperty(elementProp, "CnName", this.cnName);
            this.SetSerializedProperty(elementProp, "Name", this.enName);
            this.SetSerializedProperty(elementProp, "Info", this.info);
            this.SetSerializedProperty(elementProp, "IsPass", this.isPass);
            this.SetSerializedProperty(elementProp, "IsNeedBuild", this.isNeedBuild);
            this.SetSerializedProperty(elementProp, "AutoGenerateDirections", this.autoGenerateDirections);

            // Id 和 Type 在 OnEnable 中自动分配，此处设为 0 占位
            this.SetSerializedProperty(elementProp, "Id", 0);

            // 建造消耗
            if (this.buildCosts.Count > 0)
            {
                SerializedProperty costsProp = elementProp.FindPropertyRelative("BuildCosts");
                if (costsProp != null)
                {
                    costsProp.ClearArray();
                    for (int i = 0; i < this.buildCosts.Count; i++)
                    {
                        costsProp.InsertArrayElementAtIndex(i);
                        SerializedProperty costElem = costsProp.GetArrayElementAtIndex(i);
                        this.SetSerializedProperty(costElem, "ItemName", this.buildCosts[i].itemName);
                        this.SetSerializedProperty(costElem, "Count", this.buildCosts[i].count);
                    }
                }
            }

            so.ApplyModifiedProperties();
            EditorUtility.SetDirty(this.targetSO);
            AssetDatabase.SaveAssets();
        }

        /// <summary>
        /// 设置 SerializedProperty 值的辅助方法
        /// </summary>
        private void SetSerializedProperty(SerializedProperty parent, string fieldName, object value)
        {
            SerializedProperty prop = parent.FindPropertyRelative(fieldName);
            if (prop == null)
            {
                return;
            }

            switch (value)
            {
                case string s:
                    prop.stringValue = s;
                    break;
                case bool b:
                    prop.boolValue = b;
                    break;
                case int i:
                    prop.intValue = i;
                    break;
                case float f:
                    prop.floatValue = f;
                    break;
                case Enum e:
                    prop.intValue = Convert.ToInt32(e);
                    break;
            }
        }
    }
}
