from __future__ import annotations

from pathlib import Path
from typing import Any

from core.file_utils import (
    csharp_output_dir,
    mono_script_meta_content,
    safe_slug,
    unique_unity_asset_path,
    unity_generation_policy,
    unity_meta_path,
    write_text,
)
from core.skill import Skill


class GenerateCSharpScriptSkill(Skill):
    name = "generate_csharp_script"
    description = "Generate a safe Unity C# script into the configured Unity script folder."
    input_schema = {"task_card": "task card", "script_kind": "MonoBehaviour|ScriptableObject|PlainClass"}
    output_schema = {"generated_files": "written C# files"}

    def run(self, params: dict[str, Any], context: Any) -> dict[str, Any]:
        task_card = params.get("task_card") or {}
        selected = params.get("selected_candidate") or {}
        report_dir = Path(params.get("report_dir") or context.get("report_dir") or ".")
        base_dir = Path(context.get_service("base_dir") or ".")
        configs = context.get("configs", {}).get("unity", {})

        script_kind = params.get("script_kind") or self._infer_kind(selected)
        implementation_type = selected.get("implementation_type")
        namespace = params.get("namespace") or "RandomWorld.AgentGenerated"
        class_name = params.get("class_name") or self._class_name(selected, script_kind)
        generated_dir = csharp_output_dir(
            base_dir,
            configs,
            report_dir,
            script_kind=script_kind,
            implementation_type=implementation_type,
        )
        target = unique_unity_asset_path(generated_dir / f"{class_name}.cs")
        class_name = target.stem
        content = self._build_script(class_name, namespace, script_kind, task_card)

        target = write_text(target, content, overwrite=False)
        meta_path = None
        if unity_generation_policy(configs).get("default_output_mode", "project") != "report_only":
            meta_path = write_text(unity_meta_path(target), mono_script_meta_content(), overwrite=False)
        result = {
            "generated_files": [str(target)],
            "generated_meta_files": [str(meta_path)] if meta_path else [],
            "script_kind": script_kind,
            "namespace": namespace,
            "class_name": class_name,
            "policy": "configured_unity_path_no_overwrite",
        }
        return result

    def _infer_kind(self, selected: dict[str, Any]) -> str:
        if selected.get("implementation_type") == "runtime_feature":
            return "MonoBehaviour"
        return "PlainClass"

    def _class_name(self, selected: dict[str, Any], script_kind: str) -> str:
        if selected.get("candidate_id"):
            words = safe_slug(selected["candidate_id"], 48).split("_")
            return "".join(word.capitalize() for word in words if word) or "GeneratedUnityScript"
        return f"Generated{script_kind}"

    def _build_script(
        self,
        class_name: str,
        namespace: str,
        script_kind: str,
        task_card: dict[str, Any],
    ) -> str:
        goal = task_card.get("task_goal", "Generated Unity helper")
        if script_kind == "MonoBehaviour":
            return f"""using UnityEngine;

namespace {namespace}
{{
    /// <summary>
    /// Generated helper for: {goal}
    /// Review before copying into the Unity project.
    /// </summary>
    public sealed class {class_name} : MonoBehaviour
    {{
        [SerializeField] private bool logOnStart;

        private void Start()
        {{
            if (logOnStart)
            {{
                Debug.Log($"{{nameof({class_name})}} started.");
            }}
        }}

        public bool IsReady()
        {{
            return isActiveAndEnabled;
        }}
    }}
}}
"""
        if script_kind == "ScriptableObject":
            return f"""using UnityEngine;

namespace {namespace}
{{
    /// <summary>
    /// Generated ScriptableObject for: {goal}
    /// Review before creating assets from this type.
    /// </summary>
    [CreateAssetMenu(fileName = "{class_name}", menuName = "AgentFull/{class_name}")]
    public sealed class {class_name} : ScriptableObject
    {{
        [SerializeField] private string notes = "Generated by AgentFull.";

        public string Notes => notes;
    }}
}}
"""
        return f"""using System;

namespace {namespace}
{{
    /// <summary>
    /// Generated readonly helper for: {goal}
    /// </summary>
    public sealed class {class_name}
    {{
        public DateTime CreatedAtUtc {{ get; }} = DateTime.UtcNow;

        public string Describe()
        {{
            return "{class_name} generated by AgentFull.";
        }}
    }}
}}
"""
