#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace RandomWorld.AgentGenerated.Editor
{
    public sealed class ReadonlyAssetReferenceRiskReport : EditorWindow
    {
        private Vector2 scroll;
        private ProjectStats stats;

        [MenuItem("Tools/AgentFull/Readonly Project Overview")]
        public static void Open()
        {
            GetWindow<ReadonlyAssetReferenceRiskReport>("Agent Project Overview");
        }

        private void OnEnable()
        {
            Refresh();
        }

        private void OnGUI()
        {
            EditorGUILayout.BeginHorizontal(EditorStyles.toolbar);
            if (GUILayout.Button("Refresh", EditorStyles.toolbarButton, GUILayout.Width(80)))
            {
                Refresh();
            }

            if (GUILayout.Button("Export Markdown", EditorStyles.toolbarButton, GUILayout.Width(130)))
            {
                ExportMarkdown();
            }
            EditorGUILayout.EndHorizontal();

            if (stats == null)
            {
                EditorGUILayout.HelpBox("No stats loaded.", MessageType.Info);
                return;
            }

            scroll = EditorGUILayout.BeginScrollView(scroll);
            DrawStat("Scripts", stats.ScriptCount);
            DrawStat("Scenes", stats.SceneCount);
            DrawStat("Prefabs", stats.PrefabCount);
            DrawStat("Materials", stats.MaterialCount);
            DrawStat("Textures", stats.TextureCount);
            DrawStat("Scriptable Assets", stats.AssetFileCount);
            EditorGUILayout.Space(8);
            EditorGUILayout.HelpBox("Readonly scan. This window does not modify scenes, prefabs, or assets.", MessageType.Info);
            EditorGUILayout.EndScrollView();
        }

        private static void DrawStat(string label, int value)
        {
            EditorGUILayout.BeginHorizontal();
            EditorGUILayout.LabelField(label, GUILayout.Width(160));
            EditorGUILayout.SelectableLabel(value.ToString(), GUILayout.Height(EditorGUIUtility.singleLineHeight));
            EditorGUILayout.EndHorizontal();
        }

        private void Refresh()
        {
            stats = ProjectStats.Collect();
            Repaint();
        }

        private void ExportMarkdown()
        {
            if (stats == null)
            {
                Refresh();
            }

            string folder = "Assets/AgentFull/reports/unity_editor_exports";
            Directory.CreateDirectory(folder);
            string fileName = "project_overview_" + DateTime.Now.ToString("yyyyMMdd_HHmmss") + ".md";
            string path = Path.Combine(folder, fileName);
            File.WriteAllText(path, stats.ToMarkdown(), Encoding.UTF8);
            AssetDatabase.Refresh();
            EditorUtility.RevealInFinder(Path.GetFullPath(path));
        }

        private sealed class ProjectStats
        {
            public int ScriptCount;
            public int SceneCount;
            public int PrefabCount;
            public int MaterialCount;
            public int TextureCount;
            public int AssetFileCount;

            public static ProjectStats Collect()
            {
                return new ProjectStats
                {
                    ScriptCount = CountByExtension(".cs"),
                    SceneCount = CountByExtension(".unity"),
                    PrefabCount = CountByExtension(".prefab"),
                    MaterialCount = CountByExtension(".mat"),
                    TextureCount = CountByExtensions(new[] { ".png", ".jpg", ".jpeg", ".tga", ".psd", ".tif", ".tiff" }),
                    AssetFileCount = CountByExtension(".asset")
                };
            }

            public string ToMarkdown()
            {
                var builder = new StringBuilder();
                builder.AppendLine("# Unity Project Overview");
                builder.AppendLine();
                builder.AppendLine("| Type | Count |");
                builder.AppendLine("| --- | ---: |");
                builder.AppendLine("| Scripts | " + ScriptCount + " |");
                builder.AppendLine("| Scenes | " + SceneCount + " |");
                builder.AppendLine("| Prefabs | " + PrefabCount + " |");
                builder.AppendLine("| Materials | " + MaterialCount + " |");
                builder.AppendLine("| Textures | " + TextureCount + " |");
                builder.AppendLine("| Scriptable Assets | " + AssetFileCount + " |");
                builder.AppendLine();
                builder.AppendLine("Generated by AgentFull readonly EditorWindow.");
                return builder.ToString();
            }

            private static int CountByExtension(string extension)
            {
                if (!Directory.Exists(Application.dataPath))
                {
                    return 0;
                }

                string agentFolder = Path.DirectorySeparatorChar + "AgentFull" + Path.DirectorySeparatorChar;
                return Directory
                    .GetFiles(Application.dataPath, "*" + extension, SearchOption.AllDirectories)
                    .Count(path => path.IndexOf(agentFolder, StringComparison.OrdinalIgnoreCase) < 0);
            }

            private static int CountByExtensions(string[] extensions)
            {
                return extensions.Sum(CountByExtension);
            }
        }
    }
}
#endif
