namespace LAB2D.SO
{
    using LAB2D;
    using LAB2D.Data;
    using LAB2D.Item;
    using System.Collections.Generic;
    using UnityEngine;

    /// <summary>
    /// 创建建造物品数据。
    /// 支持方向变体自动生成：标记 AutoGenerateDirections 的条目会在运行时自动展开为 8 方向变体，
    /// 但 SO 文件本身保持干净（不持久化展开结果）。
    /// </summary>
    [CreateAssetMenu(menuName = "SO/BuildItemDataSO", order = 0)]
    public class BuildItemDataSO : ScriptableObject
    {
        /// <summary>
        /// 物品类型
        /// </summary>
        public AItem.ItemTypeEnum ItemType;

        /// <summary>
        /// 物品数据（仅包含源条目，不含自动生成的变体）
        /// </summary>
        public List<BuildItemData> BuildItemDatas;

        private static readonly int TypeInterval = 100000; // 类型间隔

        public void OnEnable()
        {
            if (this.BuildItemDatas == null)
            {
                this.BuildItemDatas = new List<BuildItemData>();
            }

            int index = ((int)this.ItemType) * TypeInterval;
            foreach (var itemData in this.BuildItemDatas)
            {
                itemData.Id = index++;
                itemData.Type = this.ItemType;
                itemData.EnsureTaskTime();
            }
        }

        /// <summary>
        /// 获取运行时展开后的物品列表（含自动生成的变体）。
        /// 此方法不修改 SO 文件本身，展开结果仅存在于内存中。
        /// </summary>
        /// <returns>展开后的 BuildItemData 列表</returns>
        public List<BuildItemData> GetExpandedItems()
        {
            var expanded = new List<BuildItemData>();
            foreach (var item in this.BuildItemDatas)
            {
                if (!item.AutoGenerateDirections)
                {
                    expanded.Add(item);
                    continue;
                }

                // 生成 8 方向变体，不保留源条目
                for (int i = 0; i < BuildItemData.DirectionCnNames.Length; i++)
                {
                    BuildItemData variant = item.Clone();
                    variant.EnName = item.EnName + "_" + i;
                    variant.CnName = BuildItemData.DirectionCnNames[i] + item.CnName;
                    expanded.Add(variant);
                }
            }

            // 统一重新分配 ID（基于展开后顺序）
            int baseId = ((int)this.ItemType) * TypeInterval;
            for (int i = 0; i < expanded.Count; i++)
            {
                expanded[i].Id = baseId + i;
                expanded[i].Type = this.ItemType;
                expanded[i].EnsureTaskTime();
            }

            return expanded;
        }
    }
}
